name: Build Android APK/AAB with Wizard Config

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
        type: string
      bundleId:
        description: 'Bundle ID'
        required: true
        type: string
      siteUrl:
        description: 'Site URL'
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Project Structure
        run: |
          # Create a completely fresh directory structure
          rm -rf android ios capacitor.config.* package*.json node_modules
          
          # Create web directory first
          mkdir -p dist
          
          # Create the HTML wrapper
          cat > dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>${{ inputs.appName }}</title>
            <style>
              body, html { margin: 0; padding: 0; height: 100%; overflow: hidden; }
              #webview { width: 100%; height: 100%; border: none; }
              .loading { display: flex; justify-content: center; align-items: center; height: 100vh; font-family: Arial, sans-serif; }
            </style>
          </head>
          <body>
            <div class="loading" id="loading">Loading...</div>
            <iframe id="webview" src="${{ inputs.siteUrl }}" style="display: none;" onload="document.getElementById('loading').style.display='none'; this.style.display='block';"></iframe>
          </body>
          </html>
          EOF

      - name: Initialize NPM Project
        run: |
          # Create package.json first
          cat > package.json << 'EOF'
          {
            "name": "mobile-app",
            "version": "1.0.0",
            "description": "${{ inputs.appName }}",
            "main": "index.js",
            "scripts": {
              "build": "echo 'Build complete'"
            },
            "dependencies": {
              "@capacitor/core": "^6.0.0",
              "@capacitor/android": "^6.0.0"
            },
            "devDependencies": {
              "@capacitor/cli": "^6.0.0",
              "typescript": "^5.0.0"
            }
          }
          EOF
          
          # Install dependencies
          npm install

      - name: Initialize Capacitor
        run: |
          # Now run cap init with proper setup
          npx cap init "${{ inputs.appName }}" "${{ inputs.bundleId }}" --web-dir=dist
          
      - name: Configure Capacitor
        run: |
          # Update the generated config
          cat > capacitor.config.ts << 'EOF'
          import { CapacitorConfig } from '@capacitor/cli';
          
          const config: CapacitorConfig = {
            appId: '${{ inputs.bundleId }}',
            appName: '${{ inputs.appName }}',
            webDir: 'dist',
            server: {
              androidScheme: 'https'
            },
            plugins: {
              SplashScreen: {
                launchShowDuration: 2000,
                backgroundColor: "#ffffff"
              }
            }
          };
          
          export default config;
          EOF

      - name: Add Android Platform
        run: |
          npx cap add android
          
      - name: Configure Android Permissions
        run: |
          # Add basic permissions
          MANIFEST_PATH="android/app/src/main/AndroidManifest.xml"
          sed -i '/<application/i\    <uses-permission android:name="android.permission.INTERNET" />' "$MANIFEST_PATH"
          sed -i '/<application/i\    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />' "$MANIFEST_PATH"
          sed -i 's/<application/<application android:hardwareAccelerated="true"/' "$MANIFEST_PATH"

      - name: Sync Capacitor
        run: npx cap sync
        
      - name: Build Android
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug bundleDebug
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-app-${{ inputs.bundleId }}-${{ github.run_number }}
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/bundle/debug/*.aab
          retention-days: 30
