name: Android Build (Lovable Capacitor)

on:
  workflow_dispatch:
    inputs:
      appName:
        description: App name (display name)
        required: false
        default: Lovable Wrapper
      bundleId:
        description: Application ID (e.g., com.example.app)
        required: false
        default: app.lovable.wrapper
      siteUrl:
        description: Website your wrapper should open
        required: false
        default: https://example.com

# Ensure the token can upload artifacts and access actions
permissions:
  contents: read
  actions: write

concurrency:
  group: android-build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Scaffold minimal Capacitor project
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p app && cd app

          # Minimal package
          npm init -y
          npm pkg set name="lovable-capacitor-app" version="1.0.0"

          # Capacitor deps
          npm i -D @capacitor/cli@latest
          npm i @capacitor/core@latest @capacitor/android@latest

          # Minimal web assets
          mkdir -p dist
          cat > dist/index.html << 'EOF'
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>Wrapper</title>
              <style>html,body{margin:0;padding:0;height:100%}iframe{border:0;width:100vw;height:100vh;display:block}</style>
            </head>
            <body>
              <iframe src="%SITE_URL%"></iframe>
            </body>
          </html>
          EOF
          sed -i "s|%SITE_URL%|${{ inputs.siteUrl || 'https://example.com' }}|g" dist/index.html

          # Capacitor config
          cat > capacitor.config.ts << 'EOF'
          import type { CapacitorConfig } from '@capacitor/cli';

          const config: CapacitorConfig = {
            appId: '%APP_ID%',
            appName: '%APP_NAME%',
            webDir: 'dist',
            server: {
              url: '%SITE_URL%',
              cleartext: true
            }
          };

          export default config;
          EOF
          sed -i "s|%APP_ID%|${{ inputs.bundleId || 'app.lovable.wrapper' }}|g" capacitor.config.ts
          sed -i "s|%APP_NAME%|${{ inputs.appName || 'Lovable Wrapper' }}|g" capacitor.config.ts
          sed -i "s|%SITE_URL%|${{ inputs.siteUrl || 'https://example.com' }}|g" capacitor.config.ts

          # Add Android platform (non-interactive)
          npx cap add android --skip-deps

          # Increase Gradle memory to avoid OOM
          sed -i 's/^org\.gradle\.jvmargs=.*/org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx2g/' android/gradle.properties || true

      - name: Build Debug APK
        working-directory: app/android
        run: ./gradlew --no-daemon assembleDebug

      - name: Try build Release AAB (optional)
        working-directory: app/android
        run: ./gradlew --no-daemon bundleRelease
        continue-on-error: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

      - name: Upload AAB artifact (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/android/app/build/outputs/bundle/release/*.aab
          if-no-files-found: ignore
