name: Build Android (Debug)

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "App Name"
        required: false
        default: "My App"
      bundleId:
        description: "Bundle ID (e.g. com.example.app)"
        required: false
        default: "com.example.app"
      siteUrl:
        description: "Your site URL (https://...)"
        required: false
        default: "https://example.com"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Prepare project (use repo if present, else bootstrap)
        run: |
          set -euo pipefail
          if [ -f package.json ]; then
            echo "Using repository project"
            npm install
          else
            echo "Bootstrapping minimal Capacitor wrapper"
            npm init -y
            npm install @capacitor/core@6 @capacitor/cli@6 @capacitor/android@6 @capacitor/status-bar@6 @capacitor/splash-screen@6

            mkdir -p dist
            cat > dist/index.html << 'EOF'
            <!doctype html>
            <html>
              <head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Capacitor Wrapper</title></head>
              <body><p>This wrapper loads your site via Capacitor server.url.</p></body>
            </html>
            EOF

            cat > capacitor.config.ts << 'EOF'
            import type { CapacitorConfig } from '@capacitor/cli';

            const config: CapacitorConfig = {
              appId: '${{ inputs.bundleId }}',
              appName: '${{ inputs.appName }}',
              webDir: 'dist',
              server: { url: '${{ inputs.siteUrl }}', cleartext: true },
              plugins: { SplashScreen: { launchShowDuration: 0 } }
            };

            export default config;
            EOF
          fi

      - name: Add Android platform (idempotent)
        run: npx cap add android || true

      - name: Sync Capacitor
        run: npx cap sync

      - name: Build Android (APK + AAB)
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug
          ./gradlew --no-daemon bundleDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            android/app/build/outputs/**/*.apk
            android/app/build/outputs/**/*.aab
