name: Build Android APK/AAB

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
        type: string
      bundleId:
        description: 'Bundle ID'
        required: true
        type: string
      siteUrl:
        description: 'Site URL'
        required: true
        type: string
      navigationMode:
        description: 'Navigation Mode'
        required: false
        type: string
        default: 'direct'
      enableTabs:
        description: 'Enable Tabs'
        required: false
        type: boolean
        default: false
      primaryHex:
        description: 'Primary Color'
        required: false
        type: string
        default: '#000000'
      accentHex:
        description: 'Accent Color'
        required: false
        type: string
        default: '#FFFFFF'
      iconPath:
        description: 'Icon Asset Path'
        required: false
        type: string
      splashPath:
        description: 'Splash Asset Path'
        required: false
        type: string
      permissionPush:
        description: 'Push Notifications Permission'
        required: false
        type: boolean
        default: false

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create assets directory
        run: mkdir -p assets

      - name: Download assets from GitHub
        if: ${{ inputs.iconPath != '' || inputs.splashPath != '' }}
        run: |
          if [ -n "${{ inputs.iconPath }}" ]; then
            echo "Downloading icon from ${{ inputs.iconPath }}"
            curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3.raw" \
                 "https://api.github.com/repos/${{ github.repository }}/contents/${{ inputs.iconPath }}" \
                 -o "assets/icon.png"
          fi
          
          if [ -n "${{ inputs.splashPath }}" ]; then
            echo "Downloading splash from ${{ inputs.splashPath }}"
            curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3.raw" \
                 "https://api.github.com/repos/${{ github.repository }}/contents/${{ inputs.splashPath }}" \
                 -o "assets/splash.png"
          fi

      - name: Create package.json with all dependencies
        run: |
          cat > package.json << 'EOF'
          {
            "name": "${{ inputs.appName }}",
            "version": "1.0.0",
            "scripts": {
              "build": "echo 'Build complete'"
            },
            "dependencies": {
              "@capacitor/android": "^6.0.0",
              "@capacitor/core": "^6.0.0",
              "@capacitor/splash-screen": "^6.0.0",
              "@capacitor/status-bar": "^6.0.0"
            },
            "devDependencies": {
              "@capacitor/cli": "^6.0.0"
            }
          }
          EOF

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install --no-fund --no-audit
          
          if [ "${{ inputs.permissionPush }}" = "true" ]; then
            npm install @capacitor/push-notifications@^6.0.0 --no-fund --no-audit
          fi

      - name: Create index.html
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>${{ inputs.appName }}</title>
              <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body, html { height: 100%; overflow: hidden; }
                  .webview-container { width: 100%; height: 100vh; border: none; }
              </style>
          </head>
          <body>
              <iframe class="webview-container" src="${{ inputs.siteUrl }}"></iframe>
              <script>
                  document.addEventListener('DOMContentLoaded', function() {
                      console.log('App loaded successfully');
                  });
              </script>
          </body>
          </html>
          EOF

      - name: Create Capacitor config
        run: |
          cat > capacitor.config.js << 'EOF'
          const config = {
            appId: '${{ inputs.bundleId }}',
            appName: '${{ inputs.appName }}',
            webDir: '.',
            server: {
              androidScheme: 'https'
            },
            plugins: {
              SplashScreen: {
                backgroundColor: '${{ inputs.primaryHex }}',
                showSpinner: false,
                androidSplashResourceName: 'splash'
              },
              StatusBar: {
                style: 'DARK',
                backgroundColor: '${{ inputs.primaryHex }}'
              }
            }
          };
          
          module.exports = config;
          EOF

      - name: Initialize Capacitor project
        run: |
          echo "Initializing Capacitor project..."
          npx cap init --web-dir=. || exit 1
          echo "Adding Android platform..."
          npx cap add android || exit 1
          echo "Syncing Capacitor..."
          npx cap sync || exit 1

      - name: Apply branding colors
        run: |
          mkdir -p android/app/src/main/res/values
          cat > android/app/src/main/res/values/colors.xml << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <color name="colorPrimary">${{ inputs.primaryHex }}</color>
              <color name="colorAccent">${{ inputs.accentHex }}</color>
              <color name="ic_launcher_background">${{ inputs.primaryHex }}</color>
          </resources>
          EOF

      - name: Copy custom assets
        run: |
          if [ -f "assets/icon.png" ]; then
            echo "Copying custom icon..."
            mkdir -p android/app/src/main/res/mipmap-hdpi
            mkdir -p android/app/src/main/res/mipmap-mdpi
            mkdir -p android/app/src/main/res/mipmap-xhdpi
            mkdir -p android/app/src/main/res/mipmap-xxhdpi
            mkdir -p android/app/src/main/res/mipmap-xxxhdpi
            
            # Copy to all density folders (in production, these should be properly resized)
            cp assets/icon.png android/app/src/main/res/mipmap-hdpi/ic_launcher.png
            cp assets/icon.png android/app/src/main/res/mipmap-mdpi/ic_launcher.png
            cp assets/icon.png android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
            cp assets/icon.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
            cp assets/icon.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          fi
          
          if [ -f "assets/splash.png" ]; then
            echo "Copying custom splash screen..."
            mkdir -p android/app/src/main/res/drawable
            cp assets/splash.png android/app/src/main/res/drawable/splash.png
          fi

      - name: Make gradlew executable
        run: |
          cd android
          chmod +x gradlew

      - name: Build APK and AAB
        run: |
          cd android
          echo "Building APK..."
          ./gradlew assembleRelease --no-daemon --stacktrace
          echo "Building AAB..."
          ./gradlew bundleRelease --no-daemon --stacktrace

      - name: Verify build outputs
        run: |
          echo "Checking for APK..."
          ls -la android/app/build/outputs/apk/release/ || echo "APK directory not found"
          echo "Checking for AAB..."
          ls -la android/app/build/outputs/bundle/release/ || echo "AAB directory not found"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: error

      - name: Clean up
        if: always()
        run: rm -rf assets
