name: Build Android (Self‑Contained)

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "Display name of your app"
        required: true
        default: "Wrap Craft"
      bundleId:
        description: "Android applicationId (e.g., com.example.app)"
        required: true
        default: "app.lovable.wrapcraft"
      siteUrl:
        description: "Your website URL to wrap (https://...)"
        required: true
        default: "https://example.com"

jobs:
  build:
    name: Android APK
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      APP_NAME: ${{ inputs.appName }}
      BUNDLE_ID: ${{ inputs.bundleId }}
      SITE_URL: ${{ inputs.siteUrl }}

    steps:
      - name: Checkout (no repo content required)
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "platforms;android-34" "build-tools;34.0.0" \
                     "platforms;android-33" "build-tools;33.0.2"

      - name: Initialize minimal project
        run: |
          set -e
          cat > package.json << 'EOF'
          {
            "name": "wrap-craft-ci",
            "version": "1.0.0",
            "private": true
          }
          EOF
          mkdir -p dist
          cat > dist/index.html << 'EOF'
          <!doctype html>
          <html><head><meta charset="utf-8"><meta name="v
