name: Build Android (Debug)

on: workflow_dispatch: inputs: appName: description: Optional app name required: false default: "" bundleId: description: Optional bundle ID (e.g., com.example.app) required: false default: "" siteUrl: description: Optional site URL to wrap required: false default: ""

jobs: build-android: runs-on: ubuntu-latest permissions: contents: write actions: write steps: - name: Checkout uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: '20'

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '17'

  - name: Install dependencies
    run: npm ci

  # Optional: if inputs were sent, gently update capacitor.config.ts
  - name: Apply optional inputs to capacitor.config.ts
    if: ${{ inputs.appName != '' || inputs.bundleId != '' || inputs.siteUrl != '' }}
    run: |
      set -e
      node - <<'EOF'
      const fs = require('fs');
      let t = fs.readFileSync('capacitor.config.ts','utf8');
      const APP_NAME = process.env.APP_NAME || '';
      const BUNDLE_ID = process.env.BUNDLE_ID || '';
      const SITE_URL = process.env.SITE_URL || '';
      if (APP_NAME) t = t.replace(/appName:\s*'[^']*'/, `appName: '${APP_NAME}'`);
      if (BUNDLE_ID) t = t.replace(/appId:\s*'[^']*'/, `appId: '${BUNDLE_ID}'`);
      if (SITE_URL) {
        // ensure server section exists for direct mode
        if (/server:/.test(t)) {
          t = t.replace(/server:\s*\{[\s\S]*?\},?/, `server: { url: '${SITE_URL}', cleartext: true },`);
        } else {
          t = t.replace(/webDir:\s*'dist',?/, `webDir: 'dist',\n  server: { url: '${SITE_URL}', cleartext: true },`);
        }
      }
      fs.writeFileSync('capacitor.config.ts', t);
      console.log('Updated capacitor.config.ts with workflow inputs (if provided).');
      EOF
    env:
      APP_NAME: ${{ inputs.appName }}
      BUNDLE_ID: ${{ inputs.bundleId }}
      SITE_URL: ${{ inputs.siteUrl }}

  - name: Add Android platform
    run: npx cap add android

  - name: Sync Capacitor
    run: npx cap sync

  - name: Build Android (APK and AAB)
    run: |
      cd android
      ./gradlew assembleDebug bundleDebug

  - name: Upload artifacts
    uses: actions/upload-artifact@v4
    with:
      name: android-artifacts
      path: |
        android/app/build/outputs/**/*.apk
        android/app/build/outputs/**/*.aab
