name: Build Android APK/AAB with Enhanced Wizard Config

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
        type: string
      bundleId:
        description: 'Bundle ID'
        required: true
        type: string
      siteUrl:
        description: 'Site URL'
        required: true
        type: string
      config:
        description: 'Full wizard configuration (JSON)'
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Parse Configuration
        id: parse_config
        run: |
          echo "Parsing wizard configuration..."
          CONFIG='${{ inputs.config }}'
          echo "Received config: $CONFIG"
          
          # Parse navigati
