name: Build Android APK/AAB

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App name'
        required: true
        default: 'WrapCraft'
      bundleId:
        description: 'Bundle ID'
        required: true
        default: 'com.wrapcraft.app'
      siteUrl:
        description: 'Site URL'
        required: true
        default: 'https://example.com'
      buildType:
        description: 'Build type'
        required: true
        default: 'apk'
        type: choice
        options:
        - apk
        - aab

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create Capacitor project
      run: |
        # Create project directory
        mkdir capacitor-app
        cd capacitor-app
        
        # Initialize npm project
        npm init -y
        
        # Install Capacitor
        npm install @capacitor/core @capacitor/cli @capacitor/android
        
        # Create basic web files
        mkdir -p www
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>${{ inputs.appName }}</title>
            <style>
                body { 
                    margin: 0; 
                    padding: 0; 
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                }
                iframe { 
                    width: 100vw; 
                    height: 100vh; 
                    border: none; 
                    display: block;
                }
            </style>
        </head>
        <body>
            <iframe src="${{ inputs.siteUrl }}" title="${{ inputs.appName }}"></iframe>
        </body>
        </html>
        EOF
        
        # Initialize Capacitor
        npx cap init "${{ inputs.appName }}" "${{ inputs.bundleId }}" --web-dir=www
        
        # Add Android platform
        npx cap add android
        
    - name: Build Android
      run: |
        cd capacitor-app
        
        # Sync web assets
        npx cap sync android
        
        # Build APK or AAB
        cd android
        if [ "${{ inputs.buildType }}" = "aab" ]; then
          ./gradlew bundleRelease
        else
          ./gradlew assembleRelease
        fi
        
    - name: Upload APK artifact
      if: inputs.buildType == 'apk'
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: capacitor-app/android/app/build/outputs/apk/release/*.apk
        
    - name: Upload AAB artifact
      if: inputs.buildType == 'aab'
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: capacitor-app/android/app/build/outputs/bundle/release/*.aab
