name: Build Android App

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: false
        default: 'MyApp'
      bundleId:
        description: 'Bundle ID'
        required: false
        default: 'com.example.app'
      siteUrl:
        description: 'Site URL'
        required: false
        default: 'https://example.com'
      buildType:
        description: 'Build Type'
        required: false
        default: 'apk'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Create Capacitor App
      run: |
        npm install -g @capacitor/core @capacitor/cli @capacitor/android
        mkdir -p android-app/www
        cd android-app
        
        cat > capacitor.config.json << EOF
        {
          "appId": "${{ github.event.inputs.bundleId }}",
          "appName": "${{ github.event.inputs.appName }}",
          "webDir": "www",
          "bundledWebRuntime": false
        }
        EOF
        
        cat > www/index.html << EOF
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>${{ github.event.inputs.appName }}</title>
        </head>
        <body style="margin:0; padding:0;">
          <iframe src="${{ github.event.inputs.siteUrl }}" 
                  style="width:100%; height:100vh; border:none;">
          </iframe>
        </body>
        </html>
        EOF
        
        cat > package.json << EOF
        {
          "name": "android-app",
          "version": "1.0.0",
          "dependencies": {
            "@capacitor/core": "^4.8.0",
            "@capacitor/android": "^4.8.0"
          }
        }
        EOF
        
        npm install
        npx cap add android
        
    - name: Build APK
      run: |
        cd android-app/android
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: android-app/android/app/build/outputs/apk/debug/app-debug.apk
